registry: registry.mdundek.network
tenantName: mdos
appName: mdos
uuid: KG75-7D58-mdos
forceUpdate: true
components:
  - name: api
    uuid: KG75-7D58-api
    image: mdos-api
    tag: latest
    imagePullSecrets:
      - name: regcred
    imagePullPolicy: Always
    services:
      - name: http
        ports:
          - name: http-3030
            port: 3030

    ingress:
      - name: http-ingress
        matchHost: mdos-api.mdundek.network
        targetPort: 3030
        trafficType: http
        
    configs:
      - name: configs
        type: env
        entries:
          - key: ROOT_DOMAIN
            value: "mdundek.network"
          - key: GEN_HELM_PATH_PATH
            value: "/usr/src/dep/mhc-generic"
          - key: ISTIO_CHART_PATH
            value: "/usr/src/dep/istio_helm/istio-control/istio-discovery"
          - key: RUN_TARGET
            value: "pod"
          - key: FTP_SERVER_MAIN_PORT
            value: "3915"
          - key: K3S_CLIENT_CA_PATH
            value: "/usr/src/dep/k3s/client-ca.crt"
          - key: K3S_CLIENT_KEY_PATH
            value: "/usr/src/dep/k3s/client-ca.key"
          - key: KC_PORT
            value: "30999"

    secrets:
      - name: creds
        type: env
        entries:
          - key: REG_USER
            value: "mdundek"
          - key: REG_PASS
            value: "li14ebe13"
      - name: k3s-ca
        type: file
        mountPath: /usr/src/dep/k3s
        entries:
          - key: client-ca
            filename: client-ca.crt
            value: |-
              -----BEGIN CERTIFICATE-----
              MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3MtY2xp
              ZW50LWNhQDE2NjQ4OTEzNzEwHhcNMjIxMDA0MTM0OTMxWhcNMzIxMDAxMTM0OTMx
              WjAjMSEwHwYDVQQDDBhrM3MtY2xpZW50LWNhQDE2NjQ4OTEzNzEwWTATBgcqhkjO
              PQIBBggqhkjOPQMBBwNCAARS1BakGbSB5JU1Pmeb7bZs39j65FvshraZQ5Z86pWb
              Q/KspeoLG+X6iYUoDChioIzCqhovAwaueL7CBo5Ybauko0IwQDAOBgNVHQ8BAf8E
              BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU2e2vB6ez7YpjURl3GEmX
              LIlIHVkwCgYIKoZIzj0EAwIDRwAwRAIgMn8EQhxBD0g/fkzACLDEIytKB9dAvOwQ
              GXbD2z2LoUkCIHLe3J8SggB4Ff8Rh5YQm1B/4wntAJfeajFjAOolVF33
              -----END CERTIFICATE-----
          - key: client-key
            filename: client-ca.key
            value: |-
              -----BEGIN EC PRIVATE KEY-----
              MHcCAQEEIK6insBao51Whvf8F6LPDWH7ht19M7vuZQwOg8eUEIYPoAoGCCqGSM49
              AwEHoUQDQgAEUtQWpBm0geSVNT5nm+22bN/Y+uRb7Ia2mUOWfOqVm0PyrKXqCxvl
              +omFKAwoYqCMwqoaLwMGrni+wgaOWG2rpA==
              -----END EC PRIVATE KEY-----
      - name: rabbitmq-creds
        type: env
        ref: rabbitmq-cluster-default-user
        entries:
          - name: RABBIT_PORT
            key: port
          - name: RABBIT_HOST
            key: host
          - name: RABBIT_USERNAME
            key: username
          - name: RABBIT_PASSWORD
            key: password
        
    volumes:
      - name: mhc-generic-chart
        mountPath: /usr/src/dep/mhc-generic
        hostPath: /home/mdundek/mdos/mdos-setup/dep/mhc-generic/chart
      - name: istiod-helm-volume
        mountPath: /usr/src/dep/istio_helm/istio-control/istio-discovery
        hostPath: /home/mdundek/mdos/mdos-setup/dep/istio_helm/istio-control/istio-discovery
          
    oidc:
      issuer: https://keycloak.mdundek.network:30999/realms/mdos
      jwksUri: https://keycloak.mdundek.network:30999/realms/mdos/protocol/openid-connect/certs
      provider: kc-mdos
      hosts:
        - mdos-api.mdundek.network
      excludePaths:
        - /registry_domain
        
    nodeSelector:
      label: mdos-stack
      value: true
