registry: registry.mdundek.network
tenantName: mdos
appName: mdos
uuid: KG75-7D58-mdos
forceUpdate: true
components:
  - name: api
    uuid: KG75-7D58-api
    image: mdos-api
    tag: latest
    imagePullSecrets:
      - name: regcred
    imagePullPolicy: Always
    services:
      - name: http
        ports:
          - name: http-3030
            port: 3030

    ingress:
      - name: http-ingress
        matchHost: mdos-api.mdundek.network
        targetPort: 3030
        trafficType: http
        
    configs:
      - name: configs
        type: env
        entries:
          - key: ROOT_DOMAIN
            value: "mdundek.network"
          - key: GEN_HELM_PATH_PATH
            value: "/usr/src/dep/mhc-generic"
          - key: ISTIO_CHART_PATH
            value: "/usr/src/dep/istio_helm/istio-control/istio-discovery"
          - key: RUN_TARGET
            value: "pod"
          - key: FTP_SERVER_MAIN_PORT
            value: "3915"
          - key: K3S_CLIENT_CA_PATH
            value: "/usr/src/dep/k3s/client-ca.crt"
          - key: K3S_CLIENT_KEY_PATH
            value: "/usr/src/dep/k3s/client-ca.key"
          - key: KC_PORT
            value: "30999"

    secrets:
      - name: creds
        type: env
        entries:
          - key: REG_USER
            value: "mdundek"
          - key: REG_PASS
            value: "li14ebe14"
      - name: k3s-ca
        type: file
        mountPath: /usr/src/dep/k3s
        entries:
          - name: client-ca
            filename: client-ca.crt
            value: |-
              -----BEGIN CERTIFICATE-----
              MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3MtY2xp
              ZW50LWNhQDE2NTk2MTg0MzgwHhcNMjIwODA0MTMwNzE4WhcNMzIwODAxMTMwNzE4
              WjAjMSEwHwYDVQQDDBhrM3MtY2xpZW50LWNhQDE2NTk2MTg0MzgwWTATBgcqhkjO
              PQIBBggqhkjOPQMBBwNCAAQrBEn/jiZ+I8HOW4WIZ8dIcvqimp921mOz+w3y5zTL
              89meFB/Rw89ErR3sq3gruFrUmzyPuLWx/UDuXC745hWRo0IwQDAOBgNVHQ8BAf8E
              BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUivl7BkMVvm56BIaExFC1
              VwAjgGwwCgYIKoZIzj0EAwIDSAAwRQIhANWWzBaEhe4Ws2e5aivmaaSo0d4DlLSw
              ocKIDktJDlVTAiB0SmoAu4y+V+WCGHmdBfCH5Iu73eJj1TlbozMUuSlczA==
              -----END CERTIFICATE-----
          - name: client-key
            filename: client-ca.key
            value: |-
              -----BEGIN EC PRIVATE KEY-----
              MHcCAQEEIOpDba6DwEB76ARAglSsmz9oq4B5+rgpOurvvKCP9prhoAoGCCqGSM49
              AwEHoUQDQgAEKwRJ/44mfiPBzluFiGfHSHL6opqfdtZjs/sN8uc0y/PZnhQf0cPP
              RK0d7Kt4K7ha1Js8j7i1sf1A7lwu+OYVkQ==
              -----END EC PRIVATE KEY-----
        
    volumes:
      - name: mhc-generic-chart
        mountPath: /usr/src/dep/mhc-generic
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/mhc-generic/chart
      - name: istiod-helm-volume
        mountPath: /usr/src/dep/istio_helm/istio-control/istio-discovery
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/istio_helm/istio-control/istio-discovery
          
    oidc:
      issuer: https://keycloak.mdundek.network:30999/realms/mdos
      jwksUri: https://keycloak.mdundek.network:30999/realms/mdos/protocol/openid-connect/certs
      provider: kc-mdos
      hosts:
        - mdos-api.mdundek.network
      excludePaths:
        - /registry_domain