registry: registry.mdundek.network
tenantName: mdos
appName: mdos
uuid: KG75-7D58-mdos
forceUpdate: true
components:
  - name: api
    uuid: KG75-7D58-api
    image: mdos-api
    tag: latest
    imagePullSecrets:
      - name: regcred
    imagePullPolicy: Always
    services:
      - name: http
        ports:
          - name: http-3030
            port: 3030

    ingress:
      - name: http-ingress
        matchHost: mdos-api.mdundek.network
        targetPort: 3030
        trafficType: http
        
    configs:
      - name: configs
        type: env
        entries:
          - key: ROOT_DOMAIN
            value: "mdundek.network"
          - key: SSL_CERT_FOLDER
            value: "/etc/letsencrypt/live/mdundek.network"
          - key: GEN_HELM_PATH_PATH
            value: "/usr/src/dep/mhc-generic"
          - key: ISTIO_CHART_PATH
            value: "/usr/src/dep/istio_helm/istio-control/istio-discovery"
          - key: RUN_TARGET
            value: "pod"
          - key: FTP_SERVER_MAIN_PORT
            value: "3915"
          - key: K3S_ROOT_CA_PATH
            value: "/usr/src/dep/k3s/server-ca.crt"
          - key: K3S_ROOT_KEY_PATH
            value: "/usr/src/dep/k3s/server-ca.key"

    secrets:
      - name: creds
        type: env
        entries:
          - key: REG_USER
            value: "mdundek"
          - key: REG_PASS
            value: "li14ebe14"
      - name: k3s-ca
        type: file
        mountPath: /usr/src/dep/k3s
        entries:
          - name: server-ca
            filename: server-ca.crt
            value: |-
              -----BEGIN CERTIFICATE-----
              MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
              dmVyLWNhQDE2NTk2MTg0MzgwHhcNMjIwODA0MTMwNzE4WhcNMzIwODAxMTMwNzE4
              WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE2NTk2MTg0MzgwWTATBgcqhkjO
              PQIBBggqhkjOPQMBBwNCAASmUUsWDDew21q8bJXWXoEr0FgVUKgvlSHniz37Tu4T
              9SdV5+QVh9dDv2D/YsYnwtuHI65Pk/vEtp7UlH27aXd9o0IwQDAOBgNVHQ8BAf8E
              BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUDSSS8F8SK17XVTjRMnkn
              nFHYwpUwCgYIKoZIzj0EAwIDRwAwRAIgE/vVSKmwiVfaDaeIqX1qu9BEKwODCKiU
              V3DpnOxpnTcCIDOcjO+a/Ngbx3cUta1zr+ApcaxU0dZV1ssoHDMkwjaO
              -----END CERTIFICATE-----
          - name: server-key
            filename: server-ca.key
            value: |-
              -----BEGIN EC PRIVATE KEY-----
              MHcCAQEEIJLgBm4OLr84ehYnA4ztMlajyE7ggcRMlmIgZ4F+pI3uoAoGCCqGSM49
              AwEHoUQDQgAEplFLFgw3sNtavGyV1l6BK9BYFVCoL5Uh54s9+07uE/UnVefkFYfX
              Q79g/2LGJ8LbhyOuT5P7xLae1JR9u2l3fQ==
              -----END EC PRIVATE KEY-----
        
    volumes:
      - name: crt-volume
        mountPath: /etc/letsencrypt/live/mdundek.network
        hostPath: /etc/letsencrypt/live/mdundek.network
      - name: mhc-generic-chart
        mountPath: /usr/src/dep/mhc-generic
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/mhc-generic/chart
      - name: istiod-helm-volume
        mountPath: /usr/src/dep/istio_helm/istio-control/istio-discovery
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/istio_helm/istio-control/istio-discovery