registry: registry.mdundek.network
tenantName: mdos
appName: mdos
uuid: KG75-7D58-mdos
forceUpdate: true
components:
  - name: api
    uuid: KG75-7D58-api
    image: mdos-api
    tag: latest
    imagePullSecrets:
      - name: regcred
    imagePullpolicy: Always
    services:
      - name: http
        ports:
          - name: http-3030
            port: 3030
      - name: tcp-ftp
        type: NodePort
        ports:
          - name: tcp-3915
            port: 3915
            nodePort: 30915
          - name: tcp-3916
            port: 3916
            nodePort: 30916
          - name: tcp-3917
            port: 3917
            nodePort: 30917
          - name: tcp-3918
            port: 3918
            nodePort: 30918
          - name: tcp-3919
            port: 3919
            nodePort: 30919
          - name: tcp-3920
            port: 3920
            nodePort: 30920
    ingress:
      - name: ingress
        matchHost: mdos-api.mdundek.network
        targetPort: 3030
        trafficType: http
        
    configs:
      - name: configs
        type: env
        entries:
          - key: ROOT_DOMAIN
            value: "mdundek.network"
          - key: SSL_CERT_FOLDER
            value: "/etc/letsencrypt/live/mdundek.network"
          - key: GEN_HELM_PATH_PATH
            value: "/usr/src/dep/mhc-generic"
          - key: ISTIO_CHART_PATH
            value: "/usr/src/dep/istio_helm/istio-control/istio-discovery"
          - key: RUN_TARGET
            value: "pod"
          - key: FTP_SERVER_MAIN_PORT
            value: "30915"
          - key: FTP_SERVER_PASV_PORT_START
            value: "30916"
          - key: FTP_SERVER_PASV_PORT_END
            value: "30920"
          - key: FTP_SERVER_TLS_KEY_PATH
            value: ""
          - key: FTP_SERVER_TLS_CA_PATH
            value: ""
          - key: FTP_SERVER_TLS_CERT_PATH
            value: ""
          - key: INBOX_ROOT_FOLDER
            value: "/usr/volume-mirror"

    secrets:
      - name: creds
        type: env
        entries:
          - key: REG_USER
            value: "mdundek"
          - key: REG_PASS
            value: "li14ebe14"
      - name: k3s-ca
        type: file
        mountPath: /usr/src/dep/k3s
        entries:
          - name: server-ca
            filename: server-ca.crt
            value: |-
              -----BEGIN CERTIFICATE-----
              MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
              dmVyLWNhQDE2NTk2MTg0MzgwHhcNMjIwODA0MTMwNzE4WhcNMzIwODAxMTMwNzE4
              WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE2NTk2MTg0MzgwWTATBgcqhkjO
              PQIBBggqhkjOPQMBBwNCAASmUUsWDDew21q8bJXWXoEr0FgVUKgvlSHniz37Tu4T
              9SdV5+QVh9dDv2D/YsYnwtuHI65Pk/vEtp7UlH27aXd9o0IwQDAOBgNVHQ8BAf8E
              BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUDSSS8F8SK17XVTjRMnkn
              nFHYwpUwCgYIKoZIzj0EAwIDRwAwRAIgE/vVSKmwiVfaDaeIqX1qu9BEKwODCKiU
              V3DpnOxpnTcCIDOcjO+a/Ngbx3cUta1zr+ApcaxU0dZV1ssoHDMkwjaO
              -----END CERTIFICATE-----
        
    volumes:
      - name: crt-volume
        mountPath: /etc/letsencrypt/live/mdundek.network
        hostPath: /etc/letsencrypt/live/mdundek.network
      - name: mhc-generic-chart
        mountPath: /usr/src/dep/mhc-generic
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/mhc-generic/chart
      - name: istiod-helm-volume
        mountPath: /usr/src/dep/istio_helm/istio-control/istio-discovery
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/istio_helm/istio-control/istio-discovery
      - name: ftp-mirror-volume
        mountPath: /usr/volume-mirror
        hostPath: /home/mdundek/.mdos/volume-mirror

    oidc:
      issuer: https://keycloak.mdundek.network/realms/mdos
      jwksUri: https://keycloak.mdundek.network/realms/mdos/protocol/openid-connect/certs
      provider: kc-mdos
      hosts:
        - mdos-api.mdundek.network
      excludePaths:
        - /registry_domain