{{- if .Values.enabled }}
{{- $appName := lower $.Values.appName }}
{{- range .Values.appComponents }}
{{- $appComponentName := lower .name -}}
{{- if and .config.enabled }}
{{- $appCompName := .name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}-{{ lower .name }}
  labels:
    {{- include "stateless-helm.labels" $ | nindent 4 }}
    {{- if $.Values.isMdosApp }}
    app: {{ $appComponentName | quote }}
    mdosAcbmAppUUID: {{ $.Values.mdosAcbmAppUUID | quote }}
    mdosAcbmAppCompUUID: {{ .mdosAcbmAppCompUUID | quote }}
    mdosAcbmAppCompName: {{ $appComponentName | quote }}
    mdosBundleName: {{ $.Values.mdosBundleName | quote }}
    {{- end }}
data:
  {{- range .config.data }}
  {{ .key }}: {{ .value | quote }}
  {{- end }}
  {{- range $.Values.global.config }}
    {{- if .appComp }}
      {{- $rangeKey := .key }}
      {{- $rangeVal := .value }}
      {{- range .appComp }}
        {{- if eq .name $appCompName }}
  {{ $rangeKey }}: {{ $rangeVal | quote }}
        {{- end }}
      {{- end }}
    {{- else }}
  {{ .key }}: {{ .value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}