{{- if .Values.enabled }}
{{- $appName := lower $.Values.appName }}
# 1 namespace per bundle per service provider
# NP must be : 
# - In 1 namespace : one label by application (networkIsolation: "private" --> fully isolated but ODM can access other apps from same bundle cannot, "$appID" --> $appCompID can access current app, "open" --> all apps from same namespace can access)
{{- range .Values.appComponents }}
{{- $appComponentName := lower .name -}}
{{ if not .skipNetworkIsolation }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $appName }}-{{ lower .name }}
  labels:
    {{- include "stateless-helm.labels" $ | nindent 4 }}
    {{- if $.Values.isMdosApp }}
    app: {{ $appComponentName | quote }}
    appUUID: {{ $.Values.appUUID | quote }}
    appCompUUID: {{ .appCompUUID | quote }}
    mdosAcbmAppCompName: {{ $appComponentName | quote }}
    tenantName: {{ $.Values.tenantName | quote }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      appUUID: {{ $.Values.appUUID | quote }}
      appCompUUID: {{ .appCompUUID | quote }}
      mdosAcbmAppCompName: {{ $appComponentName | quote }}
  {{- if eq .networkIsolation "open" }} # Allow traffic from all pods and all namespaces
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ $.Values.tenantName }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: istio-system
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: mdos
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: odm
  {{- else if eq .networkIsolation "private" }} # Deny traffic from ALL pods except system & ODM
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress: 
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: istio-system
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: mdos
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: odm
  {{- else if eq .networkIsolation "limited" }} # Allow traffic from pods within same namespace, including system, istio & ODM
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - from:
      {{- range .allowedAppComponents }}
      - podSelector:
          matchLabels:
            appCompUUID: {{ .appCompUUID }}
            mdosAcbmAppCompName: {{ .mdosAcbmAppCompName }}
            appUUID: {{ .appUUID }}
      {{- end }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: istio-system
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: mdos
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: odm
  {{- end }}
{{- end }}
{{- end }}
{{- end }}