apiVersion: v1
kind: PersistentVolume
metadata:
    name: minio-backup
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/media/backup/minio"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: minio-backup-claim
    namespace: minio-backup
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Gi
