{{- $appName := lower $.Values.appName }}

{{- range .Values.components }}
  {{- $appComponentName := lower .name -}}
  {{- $uuid := .uuid -}}
  {{- if .secrets }}
    {{- range .secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
  labels:
    app: {{ $appComponentName }}
    appUuid: {{ $.Values.uuid }}
    compUuid: {{ $uuid }}
    tenantName: {{ $.Values.tenantName }}
type: Opaque
stringData:
      {{- if eq .type "env" }}
        {{- range .entries }}
  {{ .key }}: {{ .value | quote }}
        {{- end }}
      {{- end }}
      {{- if or (eq .type "file") (eq .type "dir") }}
        {{- range .entries }}
  {{ .name }}: |-
{{ .value | indent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if $.Values.global.secrets }}
    {{- range $.Values.global.secrets }}
      {{- if .appComp }}
        {{- $secret := . }}
        {{- range .appComp }}
          {{- if eq .name $appComponentName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appName }}-{{ $appComponentName }}-{{ $secret.name }}
  labels:
    app: {{ $appComponentName }}
    appUuid: {{ $.Values.uuid }}
    compUuid: {{ $secret.uuid }}
    tenantName: {{ $.Values.tenantName }}
type: Opaque
stringData:
            {{- if eq $secret.type "env" }}
              {{- range $secret.entries }}
  {{ .key }}: {{ .value | quote }}
              {{- end }}
            {{- end }}
            {{- if or (eq $secret.type "file") (eq $secret.type "dir") }}
              {{- range $secret.entries }}
  {{ .name }}: |-
{{ .value | indent 4 }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
  labels:
    app: {{ $appComponentName }}
    appUuid: {{ $.Values.uuid }}
    compUuid: {{ .uuid }}
    tenantName: {{ $.Values.tenantName }}
type: Opaque
stringData:
        {{- if eq .type "env" }}
          {{- range .entries }}
  {{ .key }}: {{ .value | quote }}
          {{- end }}
        {{- end }}
        {{- if or (eq .type "file") (eq .type "dir") }}
          {{- range .entries }}
  {{ .name }}: |-
{{ .value | indent 4 }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}