{{- if .Values.enabled }}
{{- $appName := lower $.Values.appInternalName }}
{{- range .Values.appComponents }}
{{- $appComponentName := lower .name -}}
{{- if .autoscaling.enabled }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $appName }}-{{ lower .name }}
  labels:
    {{- include "stateless-helm.labels" $ | nindent 4 }}
    {{- if $.Values.isScdsApp }}
    scdsAcbmAppUUID: {{ $.Values.scdsAcbmAppUUID | quote }}
    scdsAcbmUUID: {{ $.Values.scdsAcbmUUID | quote }}
    scdsAcbmAppCompUUID: {{ .scdsAcbmAppCompUUID | quote }}
    scdsAcbmAppCompName: {{ $appComponentName | quote }}
    scdsBundleName: {{ $.Values.scdsBundleName | quote }}
    scdsCompanyUUID: {{ $.Values.scdsCompanyUUID | quote }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $appName }}-{{ lower .name }}
  minReplicas: {{ .autoscaling.minReplicas }}
  maxReplicas: {{ .autoscaling.maxReplicas }}
  metrics:
    {{- if .autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}