{{- if .Values.enabled }}
{{- $appName := lower $.Values.appName }}
# 2 options : mount as ENV or as file
{{- range .Values.appComponents }}
{{- $appComponentName := lower .name -}}
{{- if and .secrets.enabled }}
{{- $appCompName := .name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appName }}-{{ lower .name }}
  labels:
    {{- include "stateless-helm.labels" $ | nindent 4 }}
    {{- if $.Values.isScdsApp }}
    scdsAcbmAppUUID: {{ $.Values.scdsAcbmAppUUID | quote }}
    scdsAcbmAppCompUUID: {{ .scdsAcbmAppCompUUID | quote }}
    scdsAcbmAppCompName: {{ $appComponentName | quote }}
    scdsAcbmUUID: {{ $.Values.scdsAcbmUUID | quote }}
    scdsBundleName: {{ $.Values.scdsBundleName | quote }}
    scdsCompanyUUID: {{ $.Values.scdsCompanyUUID | quote }}
    {{- end }}
type: Opaque
data:
  {{- range .secrets.data }}
  {{ .key }}: {{ .value | b64enc }}
  {{- end }}
  {{- range $.Values.global.secrets }}
    {{- if .appComp }}
      {{- $rangeKey := .key }}
      {{- $rangeVal := .value }}
      {{- range .appComp }}
        {{- if eq .name $appCompName }}
  {{ $rangeKey }}: {{ $rangeVal | b64enc }}
        {{- end }}
      {{- end }}
    {{- else }}
  {{ .key }}: {{ .value | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}