registry: registry.mydomain.com
tenantName: mdos
appName: mdos
uuid: KG75-7D58-mdos
forceUpdate: true
components:
  - name: api
    uuid: KG75-7D58-api
    image: mdos-api
    tag: latest
    imagePullSecrets:
      - name: regcred
    services:
      - name: http
        ports:
          - name: http-3030
            port: 3030

    ingress:
      - name: ingress
        matchHost: mdos-api.mydomain.com
        targetPort: 3030
        trafficType: http
        
    configs:
      - name: configs
        type: env
        entries:
          - key: ROOT_DOMAIN
            value: "mydomain.com"
          - key: SSL_CERT_FOLDER
            value: "/etc/letsencrypt/live/mydomain.com"
          - key: GEN_HELM_PATH_PATH
            value: "/usr/src/dep/mhc-generic"
          - key: ISTIO_CHART_PATH
            value: "/usr/src/dep/istio_helm/istio-control/istio-discovery"
          - key: RUN_TARGET
            value: "pod"
          - key: FTP_SERVER_MAIN_PORT
            value: "3915"
          - key: K3S_CLIENT_CA_PATH
            value: "/usr/src/dep/k3s/client-ca.crt"
          - key: K3S_CLIENT_KEY_PATH
            value: "/usr/src/dep/k3s/client-ca.key"
          - key: KC_PORT
            value: "30999"

    secrets:
      - name: creds
        type: env
        entries:
          - key: REG_USER
            value: "mdundek"
          - key: REG_PASS
            value: "li14ebe14"
      - name: k3s-ca
        type: file
        mountPath: /usr/src/dep/k3s
        entries:
          - name: client-ca
            filename: client-ca.crt
            value: |-
              -----BEGIN CERTIFICATE-----
              -----END CERTIFICATE-----
          - name: client-key
            filename: client-ca.key
            value: |-
              -----BEGIN EC PRIVATE KEY-----
              -----END EC PRIVATE KEY-----
        
    volumes:
      - name: crt-volume
        mountPath: /etc/letsencrypt/live/mydomain.com
        hostPath: /etc/letsencrypt/live/mydomain.com
      - name: mhc-generic-chart
        mountPath: /usr/src/dep/mhc-generic
        hostPath: <path to setup folder>/dep/mhc-generic/chart
      - name: istiod-helm-volume
        mountPath: /usr/src/dep/istio_helm/istio-control/istio-discovery
        hostPath: <path to setup folder>/dep/istio_helm/istio-control/istio-discovery

    hostAliases:
      - ip: ""
        hostNames:
          - ""
          
    oidc:
      issuer: https://keycloak.mydomain.com:30999/realms/mdos
      jwksUri: https://keycloak.mydomain.com:30999/realms/mdos/protocol/openid-connect/certs
      provider: kc-mdos
      hosts:
        - mdos-api.mydomain.com
      excludePaths:
        - /registry_domain