registry: registry.mydomain.com
tenantName: mdos
appName: mdos
uuid: KG75-7D58-mdos
forceUpdate: true
components:
  - name: api
    uuid: KG75-7D58-api
    image: mdos-api
    tag: latest
    imagePullSecrets:
      - name: regcred
    services:
      - name: http
        ports:
          - name: http-3030
            port: 3030
    ingress:
      - name: ingress
        matchHost: mdos-api.mydomain.com
        targetPort: 3030
        trafficType: http
        
    configs:
      - name: configs
        type: env
        entries:
          - key: KC_HELM_CHART_DIR
            value: "/usr/src/dep/keycloak"
          - key: ROOT_DOMAIN
            value: "mydomain.com"
          - key: SSL_CERT_FOLDER
            value: "/etc/letsencrypt/live/mydomain.com"
          - key: KC_DB_ROOT
            value: "/usr/src/mdos/db"
          - key: GEN_HELM_PATH_PATH
            value: "/usr/src/dep/mhc-generic"
          - key: ISTIO_CHART_PATH
            value: "/usr/src/dep/istio_helm/istio-control/istio-discovery"
          - key: RUN_TARGET
            value: "pod"
          - key: S3_HOST
            value: "https://minio.mydomain.com"
          - key: S3_PROVIDER
            value: "minio"

    secrets:
      - name: creds
        type: env
        entries:
          - key: REG_USER
            value: "mdundek"
          - key: REG_PASS
            value: "li14ebe14"
          - key: ACCESS_KEY
            value: "REp9k63uJ6qTe4KRtMsU"
          - key: SECRET_KEY
            value: "ePFRhVookGe1SX8u9boPHoNeMh2fAO5OmTjckzFN"
      - name: k3s-ca
        type: file
        mountPath: /usr/src/dep/k3s
        entries:
          - name: server-ca
            filename: server-ca.crt
            value: |-
              -----BEGIN CERTIFICATE-----
              -----END CERTIFICATE-----
        
    volumes:
      - name: keycloak-dep
        mountPath: /usr/src/dep/keycloak
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/keycloak
      - name: keycloak-db
        mountPath: /usr/src/mdos/db
      - name: crt-volume
        mountPath: /etc/letsencrypt/live/mydomain.com
        hostPath: /etc/letsencrypt/live/mydomain.com
      - name: mhc-generic-chart
        mountPath: /usr/src/dep/mhc-generic
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/mhc-generic/chart
      - name: istiod-helm-volume
        mountPath: /usr/src/dep/istio_helm/istio-control/istio-discovery
        hostPath: /home/mdundek/workspaces/mdos/mdos-setup/dep/istio_helm/istio-control/istio-discovery

    oidc:
      issuer: https://keycloak.mydomain.com/realms/mdos
      jwksUri: https://keycloak.mydomain.com/realms/mdos/protocol/openid-connect/certs
      provider: kc-mdos
      hosts:
        - mdos-api.mydomain.com
      excludePaths:
        - /registry_domain