registry: registry.mydomain.com
mdosRegistry: registry.mydomain.com
tenantName: keycloak
appName: keycloak
uuid: KG75-7D58-keycloak
forceUpdate: true
components:
  - name: postgres
    uuid: KG75-7D58-postgres
    image: postgres
    tag: 13.2-alpine
    imagePullSecrets:
      - name: regcred
    services:
      - name: http
        ports:
          - name: port-5432
            port: 5432
    configs:
      - name: configs
        type: env
        entries:
          - key: POSTGRES_DB
            value: "keycloak"
      - name: db-init
        type: dir
        mountPath: /docker-entrypoint-initdb.d
        defaultMode: 0744
        entries:
          - key: create-multiple-postgresql-databases.sh
            value: |-
              #!/bin/bash
              set -e
              set -u
              psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
                CREATE USER $KEYCLOAK_USER password '$KEYCLOAK_PASS';
                CREATE DATABASE keycloak;
                GRANT ALL PRIVILEGES ON DATABASE keycloak TO $KEYCLOAK_USER;
              EOSQL

    secrets:
      - name: creds
        type: env
        entries:
          - key: POSTGRES_USER
            value: "admin"
          - key: POSTGRES_PASSWORD
            value: "admin"
          - key: KEYCLOAK_USER
            value: "admin"
          - key: KEYCLOAK_PASS
            value: "admin"

    volumes:
      - name: host-data-volume
        storageClass: local-path
        mountPath: /var/lib/postgresql/data
        subPath: data
        size: 5Gi

  - name: keycloak
    uuid: KG75-7D58-keycloak
    image: keycloak
    tag: 18.0.2
    commandArgs: ["start-dev"]
    imagePullSecrets:
      - name: regcred
    services:
      - name: service
        type: NodePort
        ports:
          - name: http-8080
            port: 8080
            nodePort: 30998
          - name: http-8443
            port: 8443
            svcPort: 443
            nodePort: 30999
    ingress:
      - name: ingress
        gateways: 
          - mdos/https-gateway-mdos
        matchHost: keycloak.<DOMAIN>
        targetPort: 443
        trafficType: https
    readinessProbe:
      type: http
      path: /realms/master
      port: 8080
    configs:
      - name: configs
        type: env
        entries:
          - key: KC_HTTPS_CERTIFICATE_FILE
            value: "/etc/x509/https/tls.crt"
          - key: KC_HTTPS_CERTIFICATE_KEY_FILE
            value: "/etc/x509/https/tls.key"
          - key: KC_DB
            value: "postgres"
          - key: KC_DB_URL
            value: "jdbc:postgresql://keycloak-postgres-http:5432/keycloak"
    secrets:
      - name: creds
        type: env
        entries:
          - key: KEYCLOAK_ADMIN
            value: "admin"
          - key: KEYCLOAK_ADMIN_PASSWORD
            value: "admin"
          - key: KC_DB_USERNAME
            value: "admin"
          - key: KC_DB_PASSWORD
            value: "admin"
      - name: mdos-ca
        type: dir
        mountPath: /etc/x509/https
        ref: mdos-root-domain-tls