{{- $appName := lower .Values.appName -}}

{{- range .Values.components }}
  {{- $appComponentName := lower .name -}}
  {{- $uuid := .uuid -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-{{ lower .name }}
  labels:
    app: {{ $appComponentName | quote }}
    appUuid: {{ $.Values.uuid | quote }}
    compUuid: {{ .uuid | quote }}
    tenantName: {{ $.Values.tenantName | quote }}
spec:
  {{- if .replicaCount }}
  replicas: {{ .replicaCount }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      appUuid: {{ $.Values.uuid | quote }}
      compUuid: {{ .uuid | quote }}
      app: {{ $appComponentName | quote }}
      tenantName: {{ $.Values.tenantName | quote }}
  template:

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-= POD =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}

    metadata:
      labels:
        app: {{ $appComponentName | quote }}
        appUuid: {{ $.Values.uuid | quote }}
        compUuid: {{ .uuid | quote }}
        tenantName: {{ $.Values.tenantName | quote }}
    spec:
    {{- with .imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .serviceAccount }}
      serviceAccountName: {{ $appName }}-{{ lower .name }}
    {{- end }}
    {{- with $.Values.podSecurityContext }}
      securityContext:
      {{- toYaml .podSecurityContext | nindent 8 }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-= INIT CONTAINER =-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}

    {{- $srcBuckets := "" }}
    {{- $dstPaths := "" }}
    {{- $mdosSyncs := "" }}

    {{- range .volumes }}
      {{- if .syncVolume }}
        {{- if $srcBuckets }}
          {{- $srcBuckets = print $srcBuckets  ";" .bucket -}}
          {{- $dstPaths = print $dstPaths  ";" .mountPath -}}
          {{- $mdosSyncs = print $srcBuckets  " " .syncVolume -}}
        {{- else }}
          {{- $srcBuckets = print .bucket -}}
          {{- $dstPaths = print .mountPath -}}
          {{- $mdosSyncs = print .syncVolume -}}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- if contains "true" $mdosSyncs }}
      initContainers:
      - name: {{ $appName }}-{{ lower .name }}-init
        image: {{ $.Values.registry }}/mdos-sync-container:latest
        imagePullPolicy: Always
        volumeMounts:
      {{- range .volumes }}
        {{- if .syncVolume }}
          - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
            mountPath: "{{ .mountPath }}"
        {{- end }}
      {{- end }}
        env: 
        - name: SYNC_SOURCE_BUCKET
          value: "{{ $srcBuckets }}"
        - name: SYNC_TARGET_DIR
          value: "{{ $dstPaths }}"
        - name: MINIO_HOST
          valueFrom:
            secretKeyRef:
              name: mdos-minio-creds
              key: MINIO_HOST
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mdos-minio-creds
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mdos-minio-creds
              key: MINIO_SECRET_KEY
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=--=--=-=-=-= CONTAINER =-=-=-=-=-=-=--=-=-=-=-=-=-=-=-= */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
      containers:
        - name: {{ $appName }}-{{ lower .name }}
    {{- with $.Values.securityContext }}
          securityContext:
          {{- toYaml .securityContext | nindent 12 }}
    {{- end }}
    {{- if .registry }}
          image: "{{ .registry }}/{{ .image }}:{{ .tag | default $.Chart.AppVersion }}"
    {{- else }}
          image: "{{ $.Values.registry }}/{{ .image }}:{{ .tag | default $.Chart.AppVersion }}"
    {{- end }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
    {{- if .command }}
      {{- with .command }}
          command:
          {{- toYaml . | nindent 12 }}
      {{- end }}
    {{- end }}
    {{- if .commandArgs }}
      {{- with .commandArgs }}
          args:
          {{- toYaml . | nindent 12 }}
      {{- end }}
    {{- end }}
    {{- if .workingDir }}
          workingDir: {{ .workingDir }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= ENV VARS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}

          env:

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= SECRETS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .secrets }}
      {{- range .secrets }}
        {{- $name := .name }}
        {{- if eq .type "env" }}
          {{- range .entries }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
                  key: {{ .key }}
          {{- end }}
        {{- end }}
      {{- end }}

      {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GLOBAL SECRETS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

      {{- if $.Values.global.secrets }}
        {{- range $.Values.global.secrets }}
          {{- $name := .name }}

          {{- /* -=-=-=- ENV VARS -=-=-= */}}

          {{- if eq .type "env" }}
            {{- if .appComp }}
              {{- $rangeKey := .key }}
              {{- range .appComp }}
                {{- if eq .name $appComponentName }}
            - name: {{ $rangeKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
                  key: {{ $rangeKey }}
                {{- end }}
              {{- end }}
            {{- else }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
                  key: {{ .key }}
                  {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= CONFIG-MAPS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .configs }}
      {{- range .configs }}
        {{- $name := .name }}
        {{- if eq .type "env" }}
          {{- range .entries }}
            - name: {{ .key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
                  key: {{ .key }}
          {{- end }}
        {{- end }}
      {{- end }}

      {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GLOBAL CONFIG-MAPS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

      {{- if $.Values.global.configs }}
        {{- range $.Values.global.configs }}
          {{- $name := .name }}

          {{- /* -=-=-=- ENV VARS -=-=-= */}}

          {{- if eq .type "env" }}
            {{- if .appComp }}
              {{- $rangeKey := .key }}
              {{- range .appComp }}
                {{- if eq .name $appComponentName }}
            - name: {{ $rangeKey }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
                  key: {{ $rangeKey }}
                {{- end }}
              {{- end }}
            {{- else }}
            - name: {{ .key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
                  key: {{ .key }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= PORTS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}

    {{- if .services }}
      {{- range .services }}
        {{- $svcName := .name }}
        {{- if .ports }}
          ports:
          {{- range .ports }}
          - name: {{ $svcName }}-{{ .name }}
            containerPort: {{ .port }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= LIVELINESS PROBE =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .livenessProbe }}
          livenessProbe:
      {{- if eq .livenessProbe.type "http" }}
            httpGet:
              path: {{ .livenessProbe.path }}
              port: {{ .livenessProbe.port }}
        {{- if .livenessProbe.headers }}
              httpHeaders:
          {{- range .livenessProbe.headers }}
                - name: {{ .name }}
                  value: {{ .value }}
          {{- end }}
        {{- end }}
      {{- else if eq .livenessProbe.type "tcp" }}
            tcpSocket:
              port: {{ .livenessProbe.port }}
      {{- end }}
      {{- if .livenessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
      {{- end }}
      {{- if .livenessProbe.periodSeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
      {{- end }}
      {{- if .livenessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
      {{- end }}
      {{- if .livenessProbe.successThreshold }}
            successThreshold: {{ .livenessProbe.successThreshold }}
      {{- end }}
      {{- if .livenessProbe.failureThreshold }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
      {{- end }}
    {{- end }}
          
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= READINESS PROBE =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .readinessProbe }}
          readinessProbe:
      {{- if eq .readinessProbe.type "http" }}
            httpGet:
              path: {{ .readinessProbe.path }}
              port: {{ .readinessProbe.port }}
        {{- if .readinessProbe.headers }}
              httpHeaders:
          {{- range .readinessProbe.headers }}
                - name: {{ .name }}
                  value: {{ .value }}
          {{- end }}
        {{- end }}
      {{- else if eq .readinessProbe.type "tcp" }}
            tcpSocket:
              port: {{ .readinessProbe.port }}
      {{- end }}

      {{- if .readinessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
      {{- end }}
      {{- if .readinessProbe.periodSeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
      {{- end }}
      {{- if .readinessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
      {{- end }}
      {{- if .readinessProbe.successThreshold }}
            successThreshold: {{ .readinessProbe.successThreshold }}
      {{- end }}
      {{- if .readinessProbe.failureThreshold }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-==-=-=-=-= RESSOURCES =-=-=-=-=-=-=-==-=-=-=-=-=-=-=-= */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}

    {{- if .resources }}
          resources:
          {{- toYaml .resources | nindent 12 }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-==-=-=-=-= VOLUME MOUNTS =-=-=-=-=-=-=-==-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}

          volumeMounts:

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= VOLUMES =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .volumes }}
      {{- range .volumes }}
            - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
              mountPath: {{ .mountPath }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= CONFIG MAPS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .configs }}
      {{- range .configs }}
        {{- if eq .type "file" }}
          {{- $mountPath := lower .mountPath -}}
          {{- $name := lower .name -}}
          {{- range .entries }}
            - name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
              mountPath: "{{ $mountPath }}/{{ .filename }}"
              subPath: {{ .name | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GLOBAL CONFIG MAPS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if $.Values.global.configs }}
      {{- range $.Values.global.configs }}
        {{- if eq .type "file" }}
          {{- $mountPath := lower .mountPath -}}
          {{- $config := . }}
          {{- /* -=-=-=-=-=-= CERTAIN APP COMPS ONLY =-=-=-=-=-= */}}

          {{- if .appComp }}
            {{- range .appComp }}
              {{- if eq .name $appComponentName }}
                {{- range $config.entries }}
            - name: {{ $appName }}-{{ $appComponentName }}-{{ $config.name }}
              mountPath: "{{ $mountPath }}/{{ .filename }}"
              subPath: {{ .name | quote }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- else }}

          {{- /* -=-=-=-=-=-= ALL APP COMPS =-=-=-=-=-= */}}
            {{- range .entries }}
              - name: {{ $appName }}-{{ $appComponentName }}-{{ $config.name }}
                mountPath: "{{ $mountPath }}/{{ .filename }}"
                subPath: {{ .name | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= SECRETS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .secrets }}
      {{- range .secrets }}
        {{- if eq .type "file" }}
          {{- $mountPath := lower .mountPath -}}
          {{- $name := lower .name -}}
          {{- range .entries }}
            - name: {{ $appName }}-{{ $appComponentName }}-{{ $name }}
              mountPath: "{{ $mountPath }}/{{ .filename }}"
              subPath: {{ .name | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GLOBAL SECRETS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if $.Values.global.secrets }}
      {{- range $.Values.global.secrets }}
        {{- if eq .type "file" }}
          {{- $mountPath := lower .mountPath -}}
           {{- $secret := . }}

          {{- /* -=-=-=-=-=-= CERTAIN APP COMPS ONLY =-=-=-=-=-= */}}

          {{- if .appComp }}
            {{- $entries := .entries }}
            {{- range .appComp }}
              {{- if eq .name $appComponentName }}
                {{- range $entries }}
            - name: {{ $appName }}-{{ $appComponentName }}-{{ $secret.name }}
              mountPath: "{{ $mountPath }}/{{ .filename }}"
              subPath: {{ .name | quote }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- else }}

          {{- /* -=-=-=-=-=-= ALL APP COMPS =-=-=-=-=-= */}}

            {{- range .entries }}
              - name: {{ $appName }}-{{ $appComponentName }}-{{ $secret.name }}
                mountPath: "{{ $mountPath }}/{{ .filename }}"
                subPath: {{ .name | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= VOLUMES =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}
    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */}}

      volumes:
    {{- if .volumes }}
      {{- range .volumes }}

        {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= HOSTPATH =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

        {{- if .hostPath }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          hostPath:
            path: {{ .hostPath }}
          {{- if .type }}
            type: {{ .type }}
          {{- end }}
        {{- end }}

        {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= PVC =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

        {{- if not .hostPath }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          persistentVolumeClaim:
            claimName: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
        {{- end }}

      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= CONFIG MAPS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .configs }}
      {{- range .configs }}
        {{- if eq .type "file" }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          configMap:
            name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GLOBAL CONFIG MAPS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if $.Values.global.configs }}
      {{- range $.Values.global.configs }}
        {{- if eq .type "file" }}
          {{- if .appComp }}
            {{- $config := . }}
            {{- range .appComp }}
              {{- if eq .name $appComponentName }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ $config.name }}
          configMap:
            name: {{ $appName }}-{{ $appComponentName }}-{{ $config.name }}
              {{- end }}
            {{- end }}
          {{- else }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          configMap:
            name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= SECRETS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if .secrets }}
      {{- range .secrets }}
        {{- if eq .type "file" }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          secret:
            secretName: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GLOBAL SECRETS =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

    {{- if $.Values.global.secrets }}
      {{- range $.Values.global.secrets }}
        {{- if eq .type "file" }}
          {{- if .appComp }}
            {{- $secret := . }}
            {{- range .appComp }}
              {{- if eq .name $appComponentName }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          secret:
            secretName: {{ $appName }}-{{ $appComponentName }}-{{ $secret.name }}
              {{- end }}
            {{- end }}
          {{- else }}
        - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          secret:
            secretName: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}