module.exports.CHANNEL = {
	JOB_K3S_CREATE_NAMESPACE: "k3s-create-namespace",
	JOB_K3S_DELETE_NAMESPACE: "k3s-delete-namespace",
	JOB_K3S_CREATE_SECRET: "k3s-create-secret",
	JOB_K3S_REPLACE_SECRET: "k3s-replace-secret",
	JOB_K3S_DELETE_SECRET: "k3s-delete-secret",
	JOB_K3S_CREATE_REG_SECRET: "k3s-create-reg-secret",
	JOB_K3S_APPLY_USR_ROLE_BINDINGS: "k3s-apply-usr-role-bindings",
	JOB_K3S_INSTALL_OAUTH_PROXY: "k3s-install-oauth-proxy",
	JOB_K3S_UNINSTALL_OAUTH_PROXY: "k3s-uninstall-oauth-proxy",
	JOB_K3S_ADD_ISTIO_OIDC_PROVIDER: "k3s-add-istio-oidc-provider",
	JOB_K3S_REMOVE_ISTIO_OIDC_PROVIDER: "k3s-remove-istio-oidc-provider",
	JOB_KC_CREATE_CLIENT: "kc-create-client",
	JOB_KC_DELETE_CLIENT: "kc-delete-client",
	JOB_KC_CREATE_CLIENT_SA: "kc-create-client-sa",
	JOB_KC_DELETE_CLIENT_SA: "kc-delete-client-sa",
	JOB_KC_CREATE_CLIENT_ROLES: "kc-create-client-roles",
	JOB_FTPD_CREATE_CREDENTIALS: "ftpd-create-credentials",
	JOB_FTPD_DELETE_CREDENTIALS: "ftpd-delete-credentials",
	JOB_DONE: "job-done"
}