appUUID: 58aac0f8-9e9a-4fc6-8c8f-mdos
tenantName: mdos
appName: mdos-api
appComponents:
  - name: mdos-api
    appCompUUID: 6e1edac1-8895-49a2-ba99-mdos
    replicaCount: 1
    image:
      repository: mdos-api
      tag: latest
    service:
      create: true
      type: ClusterIP
      portMappings:
        - port: 80
          containerPort: 3030
    config:
      enabled: true
      data:
        - type: env
          key: KC_HELM_CHART_DIR
          value: "/usr/src/dep/keycloak"
        - type: env
          key: ROOT_DOMAIN
          value: "mdundek.network"
        - type: env
          key: SSL_CERT_FOLDER
          value: "/etc/letsencrypt/live/mdundek.network"
        - type: env
          key: KC_DB_ROOT
          value: "/usr/src/mdos/db"
        - type: env
          key: REG_USER
          value: "mdundek"
        - type: env
          key: REG_PASS
          value: "li14ebe14"
        - type: env
          key: GEN_HELM_PATH_PATH
          value: "/usr/src/dep/mhc-generic"
        - type: env
          key: ISTIO_CHART_PATH
          value: "/usr/src/dep/istio_helm/istio-control/istio-discovery"
        - type: env
          key: RUN_TARGET
          value: "pod"
        - type: env
          key: MINIO_HOST
          value: "http://minio.mdundek.network"
        - type: env
          key: MINIO_ACCESS_KEY
          value: "REp9k63uJ6qTe4KRtMsU"
        - type: env
          key: MINIO_SECRET_KEY
          value: "ePFRhVookGe1SX8u9boPHoNeMh2fAO5OmTjckzFN"
    secrets:
      enabled: false
      data: {}
    persistence:
      enabled: true
      hostpathVolumes:
        - name: keycloak-dep-volume
          mountPath: /usr/src/dep/keycloak
          hostPath: /home/mdundek/workspaces/mdos/setup/dep/keycloak
          type: Directory
        - name: crt-volume
          mountPath: /etc/letsencrypt/live/mdundek.network
          hostPath: /etc/letsencrypt/live/mdundek.network
          type: Directory
        - name: db-volume
          mountPath: /usr/src/mdos/db
          hostPath: /home/mdundek/.mdos/db
          type: Directory
        - name: gen-helm-chart-volume
          mountPath: /usr/src/dep/mhc-generic
          hostPath: /home/mdundek/workspaces/mdos/mhc-generic/chart
          type: Directory
        - name: istiod-helm-volume
          mountPath: /usr/src/dep/istio_helm/istio-control/istio-discovery
          hostPath: /home/mdundek/workspaces/mdos/setup/dep/istio_helm/istio-control/istio-discovery
          type: Directory
        - name: k3s-crt-file
          mountPath: /usr/src/dep/k3s/server-ca.crt
          hostPath: /var/lib/rancher/k3s/server/tls/server-ca.crt
          type: File
    skipNetworkIsolation: true
    virtualService:
      - gateway: https-gateway
        hosts:
          - mdos-api.mdundek.network
        protocol: http
        svcPort: 80
        httpMatch:
          prefix: /
          port: 443
