{{- $appName := lower .Values.appName -}}

{{- range .Values.components }}
  {{- $appComponentName := lower .name -}}
  {{- $uuid := .uuid -}}
  {{- if .services }}
    {{- range .services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-{{ $appComponentName }}-{{ lower .name }}
  labels:
    app: {{ $appComponentName }}
    appUuid: {{ $.Values.uuid }}
    compUuid: {{ $uuid }}
    tenantName: {{ $.Values.tenantName }}
spec:
      {{- if .type }}
  type: {{ .type }}
      {{- else }}
  type: ClusterIP
      {{- end }}
  ports:
      {{- range .ports }}
    - targetPort: {{ .port }}
        {{- if .svcPort }}
      port: {{ .svcPort }}
        {{- else }}
      port: {{ .port }}
        {{- end }}
        {{- if .nodePort }}
      nodePort: {{ .nodePort }}
        {{- end }}
      # protocol: TCP
      name: {{ .name }}
      {{- end }}
  selector:
    appUuid: {{ $.Values.uuid }}
    compUuid: {{ $uuid }}
    app: {{ $appComponentName }}
    tenantName: {{ $.Values.tenantName }}
    {{- end }}
  {{- end }}
{{- end }}