{{- $appName := lower $.Values.appName }}
{{- range .Values.components }}
  {{- $appComponentName := lower .name -}}
  {{- $uuid := .uuid -}}
  {{- if .ingress }}
    {{- $services := .services }}
    {{- range .ingress }}

      {{- /* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GET TARGET SERVICE NAME =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= */}}

      {{- $tgPort := .targetPort }}
      {{- $svcName := "" }}
      {{- range $services }}
        {{- $tmpName := .name }}
        {{- range .ports }}
          {{ if eq .port $tgPort }}
            {{- $svcName = $tmpName -}}
          {{- end }}
        {{- end }}
      {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}
  labels:
    app: {{ $appComponentName }}
    appUuid: {{ $.Values.uuid }}
    compUuid: {{ $uuid }}
    tenantName: {{ $.Values.tenantName }}
spec:
    {{- if .gateway }}
  gateways:
    - istio-system/{{ .gateway }}
    {{- else }}
  gateways:
    - istio-system/https-gateway
    {{- end }}
  hosts:  
    - {{ .matchHost | quote -}}
      {{- if eq .trafficType "http" }}
  http:
    - name: {{ $appName }}-{{ $appComponentName }}-{{ .name }}

        {{- if .subPath }}
      match:
        - uri:
            prefix: {{ .subPath }}
          {{- if not .noRewrite }}
      rewrite:
        uri: /
          {{- end }}
        {{- end }}
      route:
      - destination:
          port:
            number: {{ .targetPort }}
          host: {{ $appName }}-{{ $appComponentName }}-{{ $svcName }}.{{ $.Release.Namespace }}.svc.cluster.local

      {{- else if or (eq .trafficType "https") (eq .trafficType "tls") }}
  tls:
    - match:
        - sniHosts: 
          - {{ .matchHost }}
      route:
      - destination:
          port:
            number: {{ .targetPort }}
          host: {{ $appName }}-{{ $appComponentName }}-{{ $svcName }}.{{ $.Release.Namespace }}.svc.cluster.local
      {{- end }}

    {{- end }}
  {{- end }}
{{- end }}